name: Unit tests 
on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24', '1.23']
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{matrix.go-version}}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@0a35821d5c230e903fcfe077583637dea1b27b47

      - name: Run unit tests and generate coverage report
        run: make test

      - name: Upload coverage report
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
         path: coverage.out
         name: Coverage-report-${{matrix.go-version}}

      - name: Display coverage test
        run: go tool cover -func=coverage.out

      - name: Build Go
        run: go build ./...
