name: Unit tests 
on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24', '1.23']
    steps:
      - name: Checkout Code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{matrix.go-version}}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@e7fa5ac41e1cf5b7d48e45e42232ce7ada589601

      - name: Run unit tests and generate coverage report
        run: make test

      - name: Upload coverage report
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
         path: coverage.out
         name: Coverage-report-${{matrix.go-version}}

      - name: Display coverage test
        run: go tool cover -func=coverage.out

      - name: Build Go
        run: go build ./...
